[package]
name = "zada-xor"
version = "1.2.2"
edition = "2024"
authors = ["Lucas Calzada <77804198+lcalzada-xor@users.noreply.github.com>"]
description = "Zero-dependency Windows NT internals: manual PE/PEB parsing, dynamic SSN extraction (Hell's Gate), indirect syscalls, and synthetic call stack spoofing in pure Rust."
license = "MIT OR Apache-2.0"
homepage = "https://github.com/lcalzada-xor/zada-xor"
documentation = "https://docs.rs/zada-xor"
repository = "https://github.com/lcalzada-xor/zada-xor"
readme = "README.md"
keywords = ["syscalls", "stack-spoofing", "ntdll", "peb", "edr-evasion"]
categories = ["os::windows-apis", "development-tools::debugging", "cryptography", "memory-management"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]

[dependencies]
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
chacha20poly1305 = "0.10"

[profile.release]
opt-level = "z"     # Optimiza agresivamente para reducir el tamaño (puedes probar "s" también)
lto = true          # Habilita Link-Time Optimization. Analiza todo el programa para eliminar código muerto entre crates
codegen-units = 1   # Reduce las unidades de generación a 1. Permite a LLVM optimizar de forma más global (a costa de compilar más lento)
panic = "abort"     # Elimina la lógica de "unwinding" (desenrollado) para pánicos. Ahorra muchísimo espacio si no necesitas capturar pánicos
strip = true        # Elimina automáticamente todos los símbolos e información de debug del binario resultante